export const portfolioData = {
  personal: {
    name: 'Suber Sulub',
    title: 'Software Developer & Tech Enthusiast',
    email: 'subeersulub10@gmail.com',
    phone: '+252636097266',
    location: 'Tech Hub, Global',
    bio: 'Full-stack developer with 3+ years of experience building scalable web applications. Passionate about creating elegant solutions to complex problems using modern technologies.',
    shortBio: 'Building elegant digital solutions with React, Next.js, and Node.js',
  },

  experience: [
    {
      id: 1,
      company: 'Prime realestate',
      position: 'Software Developer',
      duration: '2024 - 2025',
      duration_short: '1+ year',
      description: 'Worked as a software engineer focusing on backend development, developing enterprise Financial Applications.',
      achievements: [
        'Built secure and scalable RESTful APIs for enterprise financial systems',
        'Improved code quality by fixing bugs and adding backend unit tests (JUnit)',
        'Worked with Java, Node.js, TypeScript, and MongoDB in production systems',
      ],
      technologies: ['React', 'Node.js', 'SQLite', 'Java', 'typescript'],
    },
    {
      id: 2,
      company: 'Afronex Tech Hub.',
      position:  'Web developer',
      duration: '2026 - present',
      duration_short: ' 4 months',
      description: 'Developed and maintained multiple client projects from concept to deployment.',
      achievements: [
        'Assisted in developing responsive and interactive web applications.',
        'mplemented and integrated APIs for dynamic website',
        'Collaborated with the team to troubleshoot and optimize web performance',
      ],
      technologies: ['React', 'Express.js', 'MongoDB', 'JavaScript', 'HTML/CSS'],
    },
  ],

  projects: [
    {
      id: 1,
      title: 'E-Commerce Platform',
      shortDesc: 'Full-stack e-commerce solution with payment integration',
      fullDesc: 'A complete e-commerce platform featuring product catalog, shopping cart, user authentication, and Stripe payment integration. Built with React frontend and Node.js backend with PostgreSQL database.',
      image: '/ecommerce.jpg',
      tags: ['React', 'Node.js', 'Stripe', 'PostgreSQL', 'Tailwind CSS'],
      github: 'https://github.com/zupeirr/Hargeisa-Grocery',
      live: 'https://hargeisa-grocery.vercel.app/',
      features: [
        'User authentication & authorization',
        'Product search & filtering',
        'Shopping cart management',
        'Payment processing with Stripe',
        'Order tracking system',
        'Admin dashboard',
      ],
    },
    {
      id: 2,
      title: 'Real estate website',
      shortDesc: 'WebSocket-based messaging platform with notifications',
      fullDesc: 'A real-time chat application enabling instant messaging between users. Features include group chats, file sharing, typing indicators, and push notifications.',
      image: '/real-estate.jpg',
      tags: ['React', 'Node.js', 'Socket.io', 'MongoDB', 'Redux'],
      github: '#',
      live: '#',
      features: [
        'Real-time messaging with WebSockets',
        'User presence indicators',
        'Group chat functionality',
        'Message persistence',
        'File sharing',
        'Push notifications',
      ],
    },
    {
      id: 3,
      title: 'EthioRent Platform',
      shortDesc: 'EthioRent is a premium, verified real estate platform ',
      fullDesc: 'is a premium, verified real estate platform designed for the modern Ethiopian market. It integrates national identity verification (Fayda ID) and seamless payment solutions (Telebirr) to create a secure, data-driven rental experience.',
      image: '/ethiorent.jpg',
      tags: ['React 18', 'vite', 'Tailwind CSS', 'typescript'],
      github: 'https://github.com/zupeirr/EthioRent',
      live: '#',
      features: [
        'Task creation and management',
        'Team collaboration tools',
        'Progress tracking & analytics',
        'Calendar view',
        'File attachments',
        'Real-time notifications',
      ],
    },
    {
      id: 4,
      title: 'Horn Fuel Station',
      shortDesc: 'A comprehensive fuel station management system. This project provides tools for managing pumps, tanks, recording sales, generating receipts, and producing daily sales reports',
      fullDesc: 'is intended as a comprehensive solution for fuel station management. This project leverages JavaScript as the core programming language and is designed to streamline operational workflows, transactional monitoring, and facility management. With a focus on reliability, scalability, and user-friendly interfaces, Horn-Fuel-Station ',
      image: '/horn-fuel.jpg',
      tags: ['Nodejs', 'TypeScript', 'Express Api', 'React(vite)','SQLITE'],
      github: 'https://github.com/zupeirr/Horn-Fuel-Station',
      live: '#',
      features: [
        'Real-time data visualization',
        'Custom report generation',
        'Data export functionality',
        'User role-based access',
        'Performance metrics',
        'API integrations',
      ],
    },
    {
      id: 5,
      title: 'SMS',
      shortDesc: 'A robust Java console application for managing student records, utilizing MySQL, JDBC, and the DAO design pattern.',
      fullDesc: 'A robust Console-based Application built with Java and MySQL to manage student records. This project implements JDBC (Java Database Connectivity) and the DAO (Data Access Object) Design Pattern for clean architecture and maintainability.',
      image: '/sms.jpg',
      tags: ['Java', 'MySQL', 'JDBC', 'DAO', 'Console Application', 'mvc'],
      github: 'https://github.com/zupeirr/SchoolManagementSystem',
      live: '#',
      features: [
        'RESTful API architecture',
        'JWT authentication',
        'CRUD operations for student records',
        'Data validation',
        'Error handling',
        'Export to CSV functionality',
      ],
    },
  ],

  skills: {
    frontend: [
      { name: 'React', level: 95 },
      { name: 'Next.js', level: 90 },
      { name: 'JavaScript/ES6+', level: 95 },
      { name: 'TypeScript', level: 85 },
      { name: 'Tailwind CSS', level: 90 },
      { name: 'HTML/CSS', level: 95 },
      { name: 'Redux/State Management', level: 85 },
      { name: 'REST API Integration', level: 90 },
    ],
    backend: [
      { name: 'Node.js', level: 90 },
      { name: 'Express.js', level: 88 },
      { name: 'MongoDB', level: 85 },
      { name: 'PostgreSQL', level: 85 },
      { name: 'RESTful API Design', level: 90 },
      { name: 'Authentication/Authorization', level: 85 },
      { name: 'Microservices', level: 80 },
      { name: 'Firebase', level: 82 },
    ],
    tools: [
      { name: 'Git & GitHub', level: 95 },
      { name: 'Docker', level: 80 },
      { name: 'AWS', level: 78 },
      { name: 'CI/CD Pipelines', level: 82 },
      { name: 'Jest & Testing', level: 85 },
      { name: 'GraphQL', level: 75 },
      { name: 'Webpack', level: 80 },
      { name: 'Linux/Unix', level: 82 },
    ],
  },

  testimonials: [
    {
      id: 1,
      name: 'Sarah Anderson',
      role: 'Product Manager',
      company: 'TechStart Ventures',
      content: 'Suber delivered exceptional full-stack solutions that exceeded our expectations. His attention to detail and ability to understand complex requirements made him invaluable to our team.',
      rating: 5,
      avatar: '👩‍💼',
    },
    {
      id: 2,
      name: 'Michael Chen',
      role: 'CTO',
      company: 'Innovation Labs',
      content: 'Outstanding developer with deep expertise in React and Node.js. Suber not only delivered quality code but also provided valuable architectural insights that improved our entire system.',
      rating: 5,
      avatar: '👨‍💼',
    },
    {
      id: 3,
      name: 'Emma Rodriguez',
      role: 'Founder',
      company: 'Digital Ventures',
      content: 'Working with Suber was a game-changer for our startup. His full-stack expertise and proactive approach helped us launch our MVP 2 weeks ahead of schedule.',
      rating: 5,
      avatar: '👩‍🎨',
    },
    {
      id: 4,
      name: 'James Wilson',
      role: 'Engineering Lead',
      company: 'CloudTech Solutions',
      content: 'Suber brings both technical excellence and great communication skills. He seamlessly integrated with our team and delivered high-quality solutions consistently.',
      rating: 5,
      avatar: '👨‍💻',
    },
  ],

  certifications: [
    {
      id: 1,
      name: 'AWS Certified Solutions Architect',
      issuer: 'Amazon Web Services',
      date: '2023',
      credentialId: 'AWS-SAA-2023',
    },
    {
      id: 2,
      name: 'Full Stack JavaScript Certification',
      issuer: 'Coursera',
      date: '2022',
      credentialId: 'FSJ-2022-001',
    },
    {
      id: 3,
      name: 'React Advanced Patterns',
      issuer: 'Frontend Masters',
      date: '2023',
      credentialId: 'RAP-2023-002',
    },
  ],

  stats: {
    projectsCompleted: 20,
    yearsExperience: 3,
    clientsSatisfied: 30,
    codeCommits: 500,
  },

  socialLinks: {
    github: 'https://github.com/zupeirr',
    linkedin: 'https://www.linkedin.com/in/suber-sulub-147897317/',
    twitter: 'https://x.com/therealzupeirr',
    email: 'subeersulub10@gmail.com',
  },
};

export type PortfolioData = typeof portfolioData;
